# Generated by Django 5.0.4 on 2025-10-28 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_lent', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts_owed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('debtor', 'creditor')},
            },
        ),
    ]
